version: '3'

services:
  achat-devops:
    image: dorsafch/achat_dorsaf:latest # Replace with the actual Spring image and tag
    container_name: achat_dorsaf
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql:3306/achatdb?createDatabaseIfNotExist=true  # Replace with your database URL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=null
      - SPRING_JPA_HIBERNATE_DDL_AUTO= update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME= com.mysql.cj.jdbc.Driver


  mysql:
    image: mysql
    volumes:
      - ./sito/db:/var/lib/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    

