version: "3.8"

services:
  achatdb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - achatdb
    image: eyaay/achat-devops:latest  # Replace with the correct image tag
    restart: on-failure
    ports:
      - "8089:8089"
volumes:
  db:
